### PR TITLE
Initial build and directory layout

### PR DESCRIPTION
**Pull request by stuwilkins**

### CODE REVIEW

**Comment by stuwilkins** [comment]
Working now:

https://gist.github.com/e557fcf645c158869babf52ba3a631f6

**Comment by danielballan** [comment]
FYI, the gist that you posted doesn't look like it's working. I has an ImportError due to versionista.

But, I gave a :+1: to your comment above. This is a good layout, at least to start!

**Comment by stuwilkins** [comment]
Hi @danielballan I don't get that error, can you post the traceback? I have a dev install on my custom kernel. 

@danielballan @stuartcampbell when you are ok with this layout etc. can you merge? Then I will start migrating csxtools as this is a natural point to do such. I will try to set up some CI also. Are we still on the travis train?

**Comment by stuwilkins** [comment]
Sorry @danielballan my bad {:eggplant:} | sed s/egg/face/g

https://gist.github.com/22af6c4c0afa59331ed3b704aa60e4de

**Comment by danielballan** [comment]
Cool. Thanks for making and sharing `show_kernels`.

> Are we still on the travis train?

Yes. If you get as far as setting up sphinx docs, please use doctr ("documentation + Travis") a Python package which makes it easier to manage the Travis -> gh-pages process. See bluesky for an example.

@stuartcampbell I'm going to merge this to keep the wheels rolling. If we rethink the organization later, I'll take on the work on refactoring.

**Pull request merged**
